//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    public partial class Adopters
    {
        protected global::System.Web.UI.WebControls.Label lblAdopterId;
        protected global::System.Web.UI.WebControls.TextBox txtAdopterId;
        protected global::System.Web.UI.WebControls.Label lblFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.Label lblLastName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.Label lblDateOfBirth;
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.Label lblPhoneNumber;
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Label lblMaritalStatus;
        protected global::System.Web.UI.WebControls.TextBox txtMaritalStatus;
        protected global::System.Web.UI.WebControls.Label lblOccupation;
        protected global::System.Web.UI.WebControls.TextBox txtOccupation;
        protected global::System.Web.UI.WebControls.Label lblEducationLevel;
        protected global::System.Web.UI.WebControls.TextBox txtEducationLevel;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.GridView gvAdopters;
    }
}
