//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace child_a_c.Crud
{
    public partial class AdopterCrud
    {
        protected global::System.Web.UI.WebControls.Repeater rptOrphanages;
        protected global::System.Web.UI.WebControls.Panel pnlChildren;
        protected global::System.Web.UI.WebControls.Repeater rptChildren;
    }
}
