//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace child_a_c.Crud
{
    public partial class ApplicationRecords
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblOrphanageId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lblOrphanageId;

        /// <summary>
        /// lblChildId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lblChildId;

        /// <summary>
        /// txtApplicationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtApplicationDate;

        /// <summary>
        /// lblAdopterName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lblAdopterName;

        /// <summary>
        /// lblAdopterEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lblAdopterEmail;

        /// <summary>
        /// lblAdopterPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lblAdopterPhone;

        /// <summary>
        /// fuPersonalImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuPersonalImage;

        /// <summary>
        /// fuIdProof control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuIdProof;

        /// <summary>
        /// fuBirthCertificate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuBirthCertificate;

        /// <summary>
        /// fuIncomeCertificate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuIncomeCertificate;

        /// <summary>
        /// fuCasteCertificate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuCasteCertificate;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>
        /// btnBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnBack;

        /// <summary>
        /// lblSuccessMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSuccessMessage;
    }
}
